/*
 * This file is generated by jOOQ.
 */
package database.tables;


import database.Diplomski;
import database.Keys;
import database.tables.records.ProffesorRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proffesor extends TableImpl<ProffesorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>diplomski.proffesor</code>
     */
    public static final Proffesor PROFFESOR = new Proffesor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProffesorRecord> getRecordType() {
        return ProffesorRecord.class;
    }

    /**
     * The column <code>diplomski.proffesor.id</code>.
     */
    public final TableField<ProffesorRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>diplomski.proffesor.name</code>.
     */
    public final TableField<ProffesorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>diplomski.proffesor.lastname</code>.
     */
    public final TableField<ProffesorRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(45), this, "");

    private Proffesor(Name alias, Table<ProffesorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Proffesor(Name alias, Table<ProffesorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>diplomski.proffesor</code> table reference
     */
    public Proffesor(String alias) {
        this(DSL.name(alias), PROFFESOR);
    }

    /**
     * Create an aliased <code>diplomski.proffesor</code> table reference
     */
    public Proffesor(Name alias) {
        this(alias, PROFFESOR);
    }

    /**
     * Create a <code>diplomski.proffesor</code> table reference
     */
    public Proffesor() {
        this(DSL.name("proffesor"), null);
    }

    public <O extends Record> Proffesor(Table<O> child, ForeignKey<O, ProffesorRecord> key) {
        super(child, key, PROFFESOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Diplomski.DIPLOMSKI;
    }

    @Override
    public UniqueKey<ProffesorRecord> getPrimaryKey() {
        return Keys.KEY_PROFFESOR_PRIMARY;
    }

    @Override
    public Proffesor as(String alias) {
        return new Proffesor(DSL.name(alias), this);
    }

    @Override
    public Proffesor as(Name alias) {
        return new Proffesor(alias, this);
    }

    @Override
    public Proffesor as(Table<?> alias) {
        return new Proffesor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Proffesor rename(String name) {
        return new Proffesor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Proffesor rename(Name name) {
        return new Proffesor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Proffesor rename(Table<?> name) {
        return new Proffesor(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
