/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Reservations;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in diplomski.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index RESERVATIONS_ROOMFK_IDX = Internal.createIndex(DSL.name("roomfk_idx"), Reservations.RESERVATIONS, new OrderField[] { Reservations.RESERVATIONS.ROOM_UUID }, false);
    public static final Index RESERVATIONS_START_AND_STATUS = Internal.createIndex(DSL.name("start_and_status"), Reservations.RESERVATIONS, new OrderField[] { Reservations.RESERVATIONS.START_TIME, Reservations.RESERVATIONS.STATUS }, false);
    public static final Index RESERVATIONS_USERFK_IDX = Internal.createIndex(DSL.name("userfk_idx"), Reservations.RESERVATIONS, new OrderField[] { Reservations.RESERVATIONS.USER_UUID }, false);
}
