/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Reservations;
import database.tables.Room;
import database.tables.User;
import database.tables.records.ReservationsRecord;
import database.tables.records.RoomRecord;
import database.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * diplomski.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ReservationsRecord> KEY_RESERVATIONS_PRIMARY = Internal.createUniqueKey(Reservations.RESERVATIONS, DSL.name("KEY_reservations_PRIMARY"), new TableField[] { Reservations.RESERVATIONS.UUID }, true);
    public static final UniqueKey<RoomRecord> KEY_ROOM_PRIMARY = Internal.createUniqueKey(Room.ROOM, DSL.name("KEY_room_PRIMARY"), new TableField[] { Room.ROOM.UUID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.UUID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ReservationsRecord, RoomRecord> ROOMFK = Internal.createForeignKey(Reservations.RESERVATIONS, DSL.name("roomfk"), new TableField[] { Reservations.RESERVATIONS.ROOM_UUID }, Keys.KEY_ROOM_PRIMARY, new TableField[] { Room.ROOM.UUID }, true);
    public static final ForeignKey<ReservationsRecord, UserRecord> USERFK = Internal.createForeignKey(Reservations.RESERVATIONS, DSL.name("userfk"), new TableField[] { Reservations.RESERVATIONS.USER_UUID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.UUID }, true);
}
