/*
 * This file is generated by jOOQ.
 */
package database;


import database.tables.Reservations;
import database.tables.Room;
import database.tables.User;


/**
 * Convenience access to all tables in diplomski.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>diplomski.reservations</code>.
     */
    public static final Reservations RESERVATIONS = Reservations.RESERVATIONS;

    /**
     * The table <code>diplomski.room</code>.
     */
    public static final Room ROOM = Room.ROOM;

    /**
     * The table <code>diplomski.user</code>.
     */
    public static final User USER = User.USER;
}
