/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exam implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private Integer semester;
    private Integer espb;

    public Exam() {}

    public Exam(Exam value) {
        this.id = value.id;
        this.name = value.name;
        this.semester = value.semester;
        this.espb = value.espb;
    }

    public Exam(
        String id,
        String name,
        Integer semester,
        Integer espb
    ) {
        this.id = id;
        this.name = name;
        this.semester = semester;
        this.espb = espb;
    }

    /**
     * Getter for <code>diplomski.exam.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>diplomski.exam.id</code>.
     */
    public Exam setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>diplomski.exam.name</code>.
     */
    public Exam setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam.semester</code>.
     */
    public Integer getSemester() {
        return this.semester;
    }

    /**
     * Setter for <code>diplomski.exam.semester</code>.
     */
    public Exam setSemester(Integer semester) {
        this.semester = semester;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam.espb</code>.
     */
    public Integer getEspb() {
        return this.espb;
    }

    /**
     * Setter for <code>diplomski.exam.espb</code>.
     */
    public Exam setEspb(Integer espb) {
        this.espb = espb;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Exam other = (Exam) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.semester == null) {
            if (other.semester != null)
                return false;
        }
        else if (!this.semester.equals(other.semester))
            return false;
        if (this.espb == null) {
            if (other.espb != null)
                return false;
        }
        else if (!this.espb.equals(other.espb))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.semester == null) ? 0 : this.semester.hashCode());
        result = prime * result + ((this.espb == null) ? 0 : this.espb.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Exam (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(semester);
        sb.append(", ").append(espb);

        sb.append(")");
        return sb.toString();
    }
}
