/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExamTerm implements Serializable {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String examId;
    private String termId;
    private Integer studentsApplied;
    private LocalDate date;

    public ExamTerm() {}

    public ExamTerm(ExamTerm value) {
        this.uuid = value.uuid;
        this.examId = value.examId;
        this.termId = value.termId;
        this.studentsApplied = value.studentsApplied;
        this.date = value.date;
    }

    public ExamTerm(
        String uuid,
        String examId,
        String termId,
        Integer studentsApplied,
        LocalDate date
    ) {
        this.uuid = uuid;
        this.examId = examId;
        this.termId = termId;
        this.studentsApplied = studentsApplied;
        this.date = date;
    }

    /**
     * Getter for <code>diplomski.exam_term.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>diplomski.exam_term.uuid</code>.
     */
    public ExamTerm setUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam_term.exam_id</code>.
     */
    public String getExamId() {
        return this.examId;
    }

    /**
     * Setter for <code>diplomski.exam_term.exam_id</code>.
     */
    public ExamTerm setExamId(String examId) {
        this.examId = examId;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam_term.term_id</code>.
     */
    public String getTermId() {
        return this.termId;
    }

    /**
     * Setter for <code>diplomski.exam_term.term_id</code>.
     */
    public ExamTerm setTermId(String termId) {
        this.termId = termId;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam_term.students_applied</code>.
     */
    public Integer getStudentsApplied() {
        return this.studentsApplied;
    }

    /**
     * Setter for <code>diplomski.exam_term.students_applied</code>.
     */
    public ExamTerm setStudentsApplied(Integer studentsApplied) {
        this.studentsApplied = studentsApplied;
        return this;
    }

    /**
     * Getter for <code>diplomski.exam_term.date</code>.
     */
    public LocalDate getDate() {
        return this.date;
    }

    /**
     * Setter for <code>diplomski.exam_term.date</code>.
     */
    public ExamTerm setDate(LocalDate date) {
        this.date = date;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ExamTerm other = (ExamTerm) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.examId == null) {
            if (other.examId != null)
                return false;
        }
        else if (!this.examId.equals(other.examId))
            return false;
        if (this.termId == null) {
            if (other.termId != null)
                return false;
        }
        else if (!this.termId.equals(other.termId))
            return false;
        if (this.studentsApplied == null) {
            if (other.studentsApplied != null)
                return false;
        }
        else if (!this.studentsApplied.equals(other.studentsApplied))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.examId == null) ? 0 : this.examId.hashCode());
        result = prime * result + ((this.termId == null) ? 0 : this.termId.hashCode());
        result = prime * result + ((this.studentsApplied == null) ? 0 : this.studentsApplied.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExamTerm (");

        sb.append(uuid);
        sb.append(", ").append(examId);
        sb.append(", ").append(termId);
        sb.append(", ").append(studentsApplied);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
