/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proffesor implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String lastname;

    public Proffesor() {}

    public Proffesor(Proffesor value) {
        this.id = value.id;
        this.name = value.name;
        this.lastname = value.lastname;
    }

    public Proffesor(
        String id,
        String name,
        String lastname
    ) {
        this.id = id;
        this.name = name;
        this.lastname = lastname;
    }

    /**
     * Getter for <code>diplomski.proffesor.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>diplomski.proffesor.id</code>.
     */
    public Proffesor setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>diplomski.proffesor.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>diplomski.proffesor.name</code>.
     */
    public Proffesor setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>diplomski.proffesor.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>diplomski.proffesor.lastname</code>.
     */
    public Proffesor setLastname(String lastname) {
        this.lastname = lastname;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Proffesor other = (Proffesor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Proffesor (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(lastname);

        sb.append(")");
        return sb.toString();
    }
}
