/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reservations implements Serializable {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String roomUuid;
    private String userUuid;
    private String name;
    private LocalDateTime startTime;
    private String type;
    private String status;
    private String specialRequest;
    private LocalDateTime endTime;

    public Reservations() {}

    public Reservations(Reservations value) {
        this.uuid = value.uuid;
        this.roomUuid = value.roomUuid;
        this.userUuid = value.userUuid;
        this.name = value.name;
        this.startTime = value.startTime;
        this.type = value.type;
        this.status = value.status;
        this.specialRequest = value.specialRequest;
        this.endTime = value.endTime;
    }

    public Reservations(
        String uuid,
        String roomUuid,
        String userUuid,
        String name,
        LocalDateTime startTime,
        String type,
        String status,
        String specialRequest,
        LocalDateTime endTime
    ) {
        this.uuid = uuid;
        this.roomUuid = roomUuid;
        this.userUuid = userUuid;
        this.name = name;
        this.startTime = startTime;
        this.type = type;
        this.status = status;
        this.specialRequest = specialRequest;
        this.endTime = endTime;
    }

    /**
     * Getter for <code>diplomski.reservations.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>diplomski.reservations.uuid</code>.
     */
    public Reservations setUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.room_uuid</code>.
     */
    public String getRoomUuid() {
        return this.roomUuid;
    }

    /**
     * Setter for <code>diplomski.reservations.room_uuid</code>.
     */
    public Reservations setRoomUuid(String roomUuid) {
        this.roomUuid = roomUuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.user_uuid</code>.
     */
    public String getUserUuid() {
        return this.userUuid;
    }

    /**
     * Setter for <code>diplomski.reservations.user_uuid</code>.
     */
    public Reservations setUserUuid(String userUuid) {
        this.userUuid = userUuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>diplomski.reservations.name</code>.
     */
    public Reservations setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>diplomski.reservations.start_time</code>.
     */
    public Reservations setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>diplomski.reservations.type</code>.
     */
    public Reservations setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>diplomski.reservations.status</code>.
     */
    public Reservations setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.special_request</code>.
     */
    public String getSpecialRequest() {
        return this.specialRequest;
    }

    /**
     * Setter for <code>diplomski.reservations.special_request</code>.
     */
    public Reservations setSpecialRequest(String specialRequest) {
        this.specialRequest = specialRequest;
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.end_time</code>.
     */
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>diplomski.reservations.end_time</code>.
     */
    public Reservations setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Reservations other = (Reservations) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.roomUuid == null) {
            if (other.roomUuid != null)
                return false;
        }
        else if (!this.roomUuid.equals(other.roomUuid))
            return false;
        if (this.userUuid == null) {
            if (other.userUuid != null)
                return false;
        }
        else if (!this.userUuid.equals(other.userUuid))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.specialRequest == null) {
            if (other.specialRequest != null)
                return false;
        }
        else if (!this.specialRequest.equals(other.specialRequest))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.roomUuid == null) ? 0 : this.roomUuid.hashCode());
        result = prime * result + ((this.userUuid == null) ? 0 : this.userUuid.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.specialRequest == null) ? 0 : this.specialRequest.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reservations (");

        sb.append(uuid);
        sb.append(", ").append(roomUuid);
        sb.append(", ").append(userUuid);
        sb.append(", ").append(name);
        sb.append(", ").append(startTime);
        sb.append(", ").append(type);
        sb.append(", ").append(status);
        sb.append(", ").append(specialRequest);
        sb.append(", ").append(endTime);

        sb.append(")");
        return sb.toString();
    }
}
