/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Room implements Serializable {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String name;
    private String type;
    private String maximumOccupancy;
    private String equipment;

    public Room() {}

    public Room(Room value) {
        this.uuid = value.uuid;
        this.name = value.name;
        this.type = value.type;
        this.maximumOccupancy = value.maximumOccupancy;
        this.equipment = value.equipment;
    }

    public Room(
        String uuid,
        String name,
        String type,
        String maximumOccupancy,
        String equipment
    ) {
        this.uuid = uuid;
        this.name = name;
        this.type = type;
        this.maximumOccupancy = maximumOccupancy;
        this.equipment = equipment;
    }

    /**
     * Getter for <code>diplomski.room.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>diplomski.room.uuid</code>.
     */
    public Room setUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.room.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>diplomski.room.NAME</code>.
     */
    public Room setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>diplomski.room.Type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>diplomski.room.Type</code>.
     */
    public Room setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Getter for <code>diplomski.room.Maximum_occupancy</code>.
     */
    public String getMaximumOccupancy() {
        return this.maximumOccupancy;
    }

    /**
     * Setter for <code>diplomski.room.Maximum_occupancy</code>.
     */
    public Room setMaximumOccupancy(String maximumOccupancy) {
        this.maximumOccupancy = maximumOccupancy;
        return this;
    }

    /**
     * Getter for <code>diplomski.room.Equipment</code>.
     */
    public String getEquipment() {
        return this.equipment;
    }

    /**
     * Setter for <code>diplomski.room.Equipment</code>.
     */
    public Room setEquipment(String equipment) {
        this.equipment = equipment;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Room other = (Room) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.maximumOccupancy == null) {
            if (other.maximumOccupancy != null)
                return false;
        }
        else if (!this.maximumOccupancy.equals(other.maximumOccupancy))
            return false;
        if (this.equipment == null) {
            if (other.equipment != null)
                return false;
        }
        else if (!this.equipment.equals(other.equipment))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.maximumOccupancy == null) ? 0 : this.maximumOccupancy.hashCode());
        result = prime * result + ((this.equipment == null) ? 0 : this.equipment.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Room (");

        sb.append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(maximumOccupancy);
        sb.append(", ").append(equipment);

        sb.append(")");
        return sb.toString();
    }
}
