/*
 * This file is generated by jOOQ.
 */
package database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Term implements Serializable {

    private static final long serialVersionUID = 1L;

    private String uuid;
    private String name;
    private LocalDate startDate;
    private LocalDate endDate;

    public Term() {}

    public Term(Term value) {
        this.uuid = value.uuid;
        this.name = value.name;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
    }

    public Term(
        String uuid,
        String name,
        LocalDate startDate,
        LocalDate endDate
    ) {
        this.uuid = uuid;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * Getter for <code>diplomski.term.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>diplomski.term.uuid</code>.
     */
    public Term setUuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>diplomski.term.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>diplomski.term.name</code>.
     */
    public Term setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>diplomski.term.start_date</code>.
     */
    public LocalDate getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>diplomski.term.start_date</code>.
     */
    public Term setStartDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Getter for <code>diplomski.term.end_date</code>.
     */
    public LocalDate getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>diplomski.term.end_date</code>.
     */
    public Term setEndDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Term other = (Term) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.startDate == null) {
            if (other.startDate != null)
                return false;
        }
        else if (!this.startDate.equals(other.startDate))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.startDate == null) ? 0 : this.startDate.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Term (");

        sb.append(uuid);
        sb.append(", ").append(name);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);

        sb.append(")");
        return sb.toString();
    }
}
