/*
 * This file is generated by jOOQ.
 */
package database.tables.records;


import database.tables.Reservations;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationsRecord extends UpdatableRecordImpl<ReservationsRecord> implements Record9<String, String, String, String, LocalDateTime, Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>diplomski.reservations.uuid</code>.
     */
    public ReservationsRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>diplomski.reservations.room_uuid</code>.
     */
    public ReservationsRecord setRoomUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.room_uuid</code>.
     */
    public String getRoomUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diplomski.reservations.user_uuid</code>.
     */
    public ReservationsRecord setUserUuid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.user_uuid</code>.
     */
    public String getUserUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diplomski.reservations.name</code>.
     */
    public ReservationsRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diplomski.reservations.start_time</code>.
     */
    public ReservationsRecord setStartTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>diplomski.reservations.duration</code>.
     */
    public ReservationsRecord setDuration(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>diplomski.reservations.type</code>.
     */
    public ReservationsRecord setType(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>diplomski.reservations.status</code>.
     */
    public ReservationsRecord setStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>diplomski.reservations.special_request</code>.
     */
    public ReservationsRecord setSpecialRequest(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>diplomski.reservations.special_request</code>.
     */
    public String getSpecialRequest() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, LocalDateTime, Integer, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, LocalDateTime, Integer, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Reservations.RESERVATIONS.UUID;
    }

    @Override
    public Field<String> field2() {
        return Reservations.RESERVATIONS.ROOM_UUID;
    }

    @Override
    public Field<String> field3() {
        return Reservations.RESERVATIONS.USER_UUID;
    }

    @Override
    public Field<String> field4() {
        return Reservations.RESERVATIONS.NAME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Reservations.RESERVATIONS.START_TIME;
    }

    @Override
    public Field<Integer> field6() {
        return Reservations.RESERVATIONS.DURATION;
    }

    @Override
    public Field<String> field7() {
        return Reservations.RESERVATIONS.TYPE;
    }

    @Override
    public Field<String> field8() {
        return Reservations.RESERVATIONS.STATUS;
    }

    @Override
    public Field<String> field9() {
        return Reservations.RESERVATIONS.SPECIAL_REQUEST;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getRoomUuid();
    }

    @Override
    public String component3() {
        return getUserUuid();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public LocalDateTime component5() {
        return getStartTime();
    }

    @Override
    public Integer component6() {
        return getDuration();
    }

    @Override
    public String component7() {
        return getType();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getSpecialRequest();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getRoomUuid();
    }

    @Override
    public String value3() {
        return getUserUuid();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public LocalDateTime value5() {
        return getStartTime();
    }

    @Override
    public Integer value6() {
        return getDuration();
    }

    @Override
    public String value7() {
        return getType();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getSpecialRequest();
    }

    @Override
    public ReservationsRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public ReservationsRecord value2(String value) {
        setRoomUuid(value);
        return this;
    }

    @Override
    public ReservationsRecord value3(String value) {
        setUserUuid(value);
        return this;
    }

    @Override
    public ReservationsRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public ReservationsRecord value5(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public ReservationsRecord value6(Integer value) {
        setDuration(value);
        return this;
    }

    @Override
    public ReservationsRecord value7(String value) {
        setType(value);
        return this;
    }

    @Override
    public ReservationsRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ReservationsRecord value9(String value) {
        setSpecialRequest(value);
        return this;
    }

    @Override
    public ReservationsRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, Integer value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationsRecord
     */
    public ReservationsRecord() {
        super(Reservations.RESERVATIONS);
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(String uuid, String roomUuid, String userUuid, String name, LocalDateTime startTime, Integer duration, String type, String status, String specialRequest) {
        super(Reservations.RESERVATIONS);

        setUuid(uuid);
        setRoomUuid(roomUuid);
        setUserUuid(userUuid);
        setName(name);
        setStartTime(startTime);
        setDuration(duration);
        setType(type);
        setStatus(status);
        setSpecialRequest(specialRequest);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReservationsRecord
     */
    public ReservationsRecord(database.tables.pojos.Reservations value) {
        super(Reservations.RESERVATIONS);

        if (value != null) {
            setUuid(value.getUuid());
            setRoomUuid(value.getRoomUuid());
            setUserUuid(value.getUserUuid());
            setName(value.getName());
            setStartTime(value.getStartTime());
            setDuration(value.getDuration());
            setType(value.getType());
            setStatus(value.getStatus());
            setSpecialRequest(value.getSpecialRequest());
            resetChangedOnNotNull();
        }
    }
}
